"""Incident report generation: scan results -> markdown."""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from .models import Analysis, EncryptMode
from .scanner import ScanResult


def _human(n: int) -> str:
    x = float(n)
    for unit in ("B", "KiB", "MiB", "GiB", "TiB"):
        if x < 1024 or unit == "TiB":
            return f"{x:,.1f} {unit}" if unit != "B" else f"{int(x):,} B"
        x /= 1024
    return f"{x:,.1f} TiB"


def _pct(ratio: float) -> str:
    return f"{ratio * 100:.1f}%"


def _mode_label(analysis: Analysis) -> str:
    if analysis.mode is None:
        return "n/a"
    return {
        EncryptMode.FULL: "FULL",
        EncryptMode.PARTLY: f"PARTLY {analysis.footer.data_percent}%",
        EncryptMode.HEADER: "HEADER (1 MiB)",
    }.get(analysis.mode, analysis.mode.name)


def generate_report(result: ScanResult, title: str = "Ransomware Incident Triage Report") -> str:
    stats = result.stats
    lines: list[str] = []
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines.append(f"# {title}")
    lines.append("")
    lines.append(f"*Generated by ransomforensics on {now}*")
    lines.append(f"*Scanned root:* `{result.root}`")
    lines.append("")

    # -- executive summary -------------------------------------------------
    lines.append("## Executive summary")
    lines.append("")
    if stats.files_matched == 0:
        lines.append(
            f"No known-family encrypted-file footers were found among the "
            f"{stats.files_seen:,} files examined. Either this directory was "
            "not hit by a supported family, or the encryptor strips its "
            "footer after finishing."
        )
    else:
        families = ", ".join(
            f"**{fam}** ({count} file{'s' if count != 1 else ''})"
            for fam, count in sorted(stats.by_family.items())
        )
        lines.append(
            f"{stats.files_matched:,} of {stats.files_seen:,} files carry a "
            f"known ransomware footer: {families}."
        )
        lines.append("")
        rec_ratio = _pct(stats.recoverable_ratio)
        lines.append(
            f"**{_human(stats.total_recoverable_bytes)} of "
            f"{_human(stats.total_original_bytes)} matched original data "
            f"({rec_ratio}) was never encrypted and is recoverable without "
            "any key.** These regions can be carved immediately; they do not "
            "depend on a decryptor, a seized key set, or negotiation."
        )
    lines.append("")

    # -- numbers table ------------------------------------------------------
    lines.append("## Totals")
    lines.append("")
    lines.append("| metric | value |")
    lines.append("|---|---|")
    lines.append(f"| files seen | {stats.files_seen:,} |")
    lines.append(f"| family-matched | {stats.files_matched:,} |")
    lines.append(f"| unmatched | {stats.files_unmatched:,} |")
    lines.append(f"| skipped (too small / unreadable) | {stats.files_skipped:,} |")
    lines.append(f"| original data in matched files | {_human(stats.total_original_bytes)} |")
    lines.append(f"| keyless-recoverable | **{_human(stats.total_recoverable_bytes)} ({_pct(stats.recoverable_ratio)})** |")
    lines.append("")

    if stats.by_family:
        lines.append("## Family breakdown")
        lines.append("")
        lines.append("| family | files | keyless-recoverable |")
        lines.append("|---|---|---|")
        for fam in sorted(stats.by_family):
            rec = stats.recoverable_by_family.get(fam, 0)
            lines.append(
                f"| {fam} | {stats.by_family[fam]:,} | {_human(rec)} |"
            )
        lines.append("")

    # -- most valuable recovery targets -------------------------------------
    ranked = sorted(
        result.analyses,
        key=lambda a: a.recoverable_without_key_bytes,
        reverse=True,
    )
    top = [a for a in ranked if a.recoverable_without_key_bytes > 0][:25]
    if top:
        lines.append("## Top recovery targets")
        lines.append("")
        lines.append("Files below carry the largest untouched plaintext "
                     "regions; carve these first.")
        lines.append("")
        lines.append("| file | mode | original | recoverable | ratio |")
        lines.append("|---|---|---|---|---|")
        for a in top:
            lines.append(
                f"| `{Path(a.path).name}` | {_mode_label(a)} | "
                f"{_human(a.original_size)} | "
                f"{_human(a.recoverable_without_key_bytes)} | "
                f"{_pct(a.recoverable_ratio)} |"
            )
        lines.append("")

    # -- per-file appendix ---------------------------------------------------
    if result.analyses:
        lines.append("## Per-file detail")
        lines.append("")
        lines.append("<details><summary>expand full file list</summary>")
        lines.append("")
        for a in result.analyses:
            lines.append(f"#### `{a.path}`")
            lines.append("")
            lines.append(f"- family: **{a.family}** (detected by: {a.detected_by})")
            lines.append(f"- original size: {_human(a.original_size)}")
            lines.append(f"- mode: {_mode_label(a)}")
            if a.encrypted:
                enc = a.encrypted[0]
                lines.append(
                    f"- encrypted range: `[0, {enc.end:#x})` "
                    f"({_human(enc.length)}, {enc.cipher}, wrapped by {enc.key_wrapped_by})"
                )
            for region in a.plaintext:
                lines.append(
                    f"- untouched range: `[{region.start:#x}, {region.end:#x})` "
                    f"({_human(region.length)})"
                )
            lines.append("")
        lines.append("</details>")
        lines.append("")

    if result.errors:
        lines.append("## Scan errors")
        lines.append("")
        for path, reason in result.errors[:50]:
            lines.append(f"- `{path}`: {reason}")
        lines.append("")

    lines.append("## Method")
    lines.append("")
    lines.append(
        "Family identification is structural: each parser validates the "
        "trailing metadata the encryptor appends to every locked file. "
        "Keyless recovery exploits partial encryption: to hit terabytes "
        "quickly, encryptors only touch a fraction of each large file and "
        "leave the remainder untouched on disk. The footer records exactly "
        "which fraction, so the untouched regions can be carved verbatim. "
        "No malware binary is executed, downloaded, or required."
    )
    lines.append("")
    return "\n".join(lines)


def write_report(result: ScanResult, out: Path | str, title: str | None = None) -> Path:
    out = Path(out)
    text = generate_report(result, title=title) if title else generate_report(result)
    out.write_text(text, encoding="utf-8")
    return out
